collections:
  members:
    output: true


defaults:
  - scope:
      path: ""
      type: "members"
    values:
      layout: "member"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "quotes"
    values:
      layout: "quote"

baseurl: /super-chat